### ISSUE TITLE
MVS issue

### ISSUE THREAD

**Issue by MLB320** [TIDOP-USAL/graphos#20]
When I try to generate the dense point cloud with the MVS, the process crashes and I receive the following error message. 

20/Oct/2023 15:09:29Error: Exception trace:
20/Oct/2023 15:09:29Error: >> MVS error (mvs.cpp:660, execute)
20/Oct/2023 15:09:29Error: >> (mvs.cpp:568, exportToMVS)
20/Oct/2023 15:09:29Error: >> Assertion 'model.exists()' failed. model.mvs not found (mvs.cpp:565, exportToMVS

Which is the problem?

**Comment by estebanrdo** [comment]
It seems that the issue occurs when converting to the OpenMVS format. Could you share the complete log file and the contents of the 'dense/mvs/temp' path?

**Comment by MLB320** [comment]
Dear Esteban

thank you for your reply.
I am sharing with you a complete project. https://we.tl/t-MkPQA7f1sD
I have tried with different datasets and always got the same error.
I also tried the CMVS/PMVS algorithm, but everything worked fine in this case. I have not yet tried the algorithm Shading-Aware MVS.
Regards
Mauro



------
Prof. Mauro Lo Brutto
Dipartimento di Ingegneria
Sezione Strutture e Infrastrutture
Università di Palermo
Viale delle Scienze - Edificio 8
90128 - PALERMO (Italy)
email: ***@***.***

________________________________
Da: Esteban Ruiz de Oña Crespo ***@***.***>
Inviato: sabato 21 ottobre 2023 11:15
A: TIDOP-USAL/graphos ***@***.***>
Cc: MAURO LO BRUTTO ***@***.***>; Author ***@***.***>
Oggetto: Re: [TIDOP-USAL/graphos] MVS issue (Issue #20)


It seems that the issue occurs when converting to the OpenMVS format. Could you share the complete log file and the contents of the 'dense/mvs/temp' path?

**Comment by estebanrdo** [comment]
Thank you Mauro for sharing the project. I have tested it on my computer and it generates the point cloud correctly. The error may be due to the absence of some necessary DLLs for OpenMVS. To check if this is the case or if it's another error, you can try to run directly the OpenMVS commands used from GRAPHOS (if the installation path is different from "C:\Program Files\graphos\bin" you will need to change it).

To convert to OpenMVS format:

"C:\Program Files\graphos\bin\OpenMVS\InterfaceCOLMAP.exe" -i "C:\Users\Mauro\Documents\GRAPHOS\Projects\sangalgano\dense\mvs\temp\export" -o "C:\Users\Mauro\Documents\GRAPHOS\Projects\sangalgano\dense\mvs\temp\model.mvs"

Point cloud densification with Cuda:

"C:\Program Files\graphos\bin\OpenMVS\DensifyPointCloud.exe" -w "C:\Users\Mauro\Documents\GRAPHOS\Projects\sangalgano\dense\mvs\temp" -i model.mvs -o model_dense.mvs -v 0 --resolution-level 1 --min-resolution 640 --max-resolution 3000 --number-views 8 --number-views-fuse 5 --cuda-device -1

Point cloud densification without Cuda:

"C:\Program Files\graphos\bin\OpenMVS\DensifyPointCloud.exe" -w "C:\Users\Mauro\Documents\GRAPHOS\Projects\sangalgano\dense\mvs\temp" -i model.mvs -o model_dense.mvs -v 0 --resolution-level 1 --min-resolution 640 --max-resolution 3000 --number-views 5 --number-views-fuse 3 --cuda-device -2

**Comment by MLB320** [comment]
I have tried running OpenMVS commands directly using windows powershell but I am unable to execute the commands. I don't know if I'm doing something wrong with the command syntax. Could you give me more detailed information?
I have also tried Graphos on another pc with the same dataset and everything works correctly. Surely the problem must be in my PC.
Regards
Mauro



________________________________
Da: Esteban Ruiz de Oña Crespo ***@***.***>
Inviato: martedì 24 ottobre 2023 10:30
A: TIDOP-USAL/graphos ***@***.***>
Cc: MAURO LO BRUTTO ***@***.***>; Author ***@***.***>
Oggetto: Re: [TIDOP-USAL/graphos] MVS issue (Issue #20)


Thank you Mauro for sharing the project. I have tested it on my computer and it generates the point cloud correctly. The error may be due to the absence of some necessary DLLs for OpenMVS. To check if this is the case or if it's another error, you can try to run directly the OpenMVS commands used from GRAPHOS (if the installation path is different from "C:\Program Files\graphos\bin" you will need to change it).

To convert to OpenMVS format:

"C:\Program Files\graphos\bin\OpenMVS\InterfaceCOLMAP.exe" -i "C:\Users\Mauro\Documents\GRAPHOS\Projects\sangalgano\dense\mvs\temp\export" -o "C:\Users\Mauro\Documents\GRAPHOS\Projects\sangalgano\dense\mvs\temp\model.mvs"

Point cloud densification with Cuda:

"C:\Program Files\graphos\bin\OpenMVS\DensifyPointCloud.exe" -w "C:\Users\Mauro\Documents\GRAPHOS\Projects\sangalgano\dense\mvs\temp" -i model.mvs -o model_dense.mvs -v 0 --resolution-level 1 --min-resolution 640 --max-resolution 3000 --number-views 8 --number-views-fuse 5 --cuda-device -1

Point cloud densification without Cuda:

"C:\Program Files\graphos\bin\OpenMVS\DensifyPointCloud.exe" -w "C:\Users\Mauro\Documents\GRAPHOS\Projects\sangalgano\dense\mvs\temp" -i model.mvs -o model_dense.mvs -v 0 --resolution-level 1 --min-resolution 640 --max-resolution 3000 --number-views 5 --number-views-fuse 3 --cuda-device -2

**Comment by estebanrdo** [comment]
Hi Mauro,

I have compiled a new version of GRAPHOS with some changes in the densification:
[GRAPHOS 2.0.0 Beta 5](https://usales-my.sharepoint.com/:u:/g/personal/estebanrdo_usal_es/EVPxbcaUvxRFji0FrrwADZoB20Uv410F6YgjIfGOw-e1fg?e=y1BahZ)

I have replaced the OpenMVS version and removed a few files so you better uninstall the previous version of GRAPHOS. I hope everything works well now.

Regards,
Esteban

**Comment by MLB320** [comment]
Dear Esteban

now all seems to be ok. Many thanks for your support.

If I may suggest an improvement, I think it would be very useful to have a command to limit the area of interest for the dense cloud calculation.

Kind regards,
Mauro

------
Prof. Mauro Lo Brutto
Dipartimento di Ingegneria
Sezione Strutture e Infrastrutture
Università di Palermo
Viale delle Scienze - Edificio 8
90128 - PALERMO (Italy)
email: ***@***.***

________________________________
Da: Esteban Ruiz de Oña Crespo ***@***.***>
Inviato: lunedì 6 novembre 2023 18:19
A: TIDOP-USAL/graphos ***@***.***>
Cc: MAURO LO BRUTTO ***@***.***>; Author ***@***.***>
Oggetto: Re: [TIDOP-USAL/graphos] MVS issue (Issue #20)


Hi Mauro,

I have compiled a new version of GRAPHOS with some changes in the densification:
GRAPHOS 2.0.0 Beta 5<https://usales-my.sharepoint.com/:u:/g/personal/estebanrdo_usal_es/EVPxbcaUvxRFji0FrrwADZoB20Uv410F6YgjIfGOw-e1fg?e=y1BahZ>

I have replaced the OpenMVS version and removed a few files so you better uninstall the previous version of GRAPHOS. I hope everything works well now.

Regards,
Esteban

**Comment by estebanrdo** [comment]
Thank you for the tests!

All suggestions are welcome. We are currently focused on releasing the stable 2.0 version, but we will add new features afterward. The feature you mentioned is interesting, so we will try to implement it.
 
Regards,
Esteban
